sudo: required
services:
  - docker

before_install:
  - docker build -t matiastassara/Docker-TravisCI -f Dockerfile.dev .

script:
  - docker run matiastassara/Docker-TravisCI npm run test -- --coverage
